#!/bin/bash

###Written by: Jeevan @ 15-10-18

###color variables
bold=$(echo "\e[1m")
red=$(echo  "\e[1;31m")
green=$(echo  "\e[1;32m")
yellow=$(echo  "\e[1;33m")
bgred=$(echo "\e[1;41m")
bggren=$(echo "\e[1;42m")
bgyelow=$(echo "\e[1;43m")
bgskbue=$(echo "\e[1;46m")
bgper=$(echo "\e[1;44m")
cle=$(echo  "\e[0m")


clear
##file verification
if [ -z $1 ]
then
    echo "`basename $0` <file>"
    exit 1
fi

if [ ! -r $1 ] 
then
   echo "Cannot open file"
   exit 1
fi

##menu 
echo
echo -e "\t\v$bold 1.Create The $bgred Files $cle $bold From File:$fn $cle"
echo -e "\t\v$bold 2.Create The $bggren Folders $cle $bold From File:$fn $cle"
echo -e "\t\v$bold 3.Create The $bgyelow Folder & File $cle $bol Form File:$fn $cle"
echo -e "\t\v$bold 4.Add The $bgskbue Sequence info to All File $cle $bold Form File:$fn $bold"
echo -e "\t\vEnter The Following $bgper Option No$cle"
read op

clear 

case $op in
	
	1)	
		for i  in `cat $1`
		do
			touch $i.txt
		done
		;;
	2)
		for i  in `cat $1`
		do
			mkdir $i
		done
		;;

	3)
		read -p "Would U Like To Create The File Inside The Folders?? [y/n]" ch
		clear

		if [ $ch = "y" ]; then
		
			for i in  ` cat $1`
			do
				mkdir $i
				touch $i/$i.txt
			done

		else

			for i in `cat $1`
			do
				mkdir $i
				touch $i.txt
			done
		fi
		;;
	4)
		clear
		echo -e "MODES\n"
		echo -e "1.Interactive Mode [To Enter Continue Input]\n"
		echo -e "2.Normal Mode [To Enter Single Input]\n"
		echo -e "mode?!!\n"
		read mod
		case $mod in
			
			1)
				while true
				do
				clear

				echo "Enter The Input To add On File [press q To Exit The Mode]"  	
				read "msg"
			
				if [ $msg = " " ]; then 
				       echo "don't leave the space without input"     
				elif [ $msg = "q" ]; then 
					break
				else	
					for i in `cat $1`
					do
						echo "$msg" >> "$i.txt"
					done
				fi
				done
				;;
			2)

				echo "Enter The MESSEGE"
				read "msg"

					for i  in `cat $1`
					do
						echo "$msg" >> "$i.txt"
					done
						;;
	esac
esac


